services:
  # Backend API
  - type: web
    name: trexo-robotics-api
    env: python
    branch: master     # change to master if needed
    buildCommand: pip install -r requirements.txt
    startCommand: python api/data_api.py
    region: oregon
    envVars:
      - key: ENV
        value: production

  # Dashboard static site
  - type: web
    name: trexo-robotics-dashboard
    env: static
    branch: main     # change to master if needed
    buildCommand: ""
    staticPublishPath: dashboard
    plan: free
